# Generated by Django 4.2.5 on 2023-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('1', 'classic'), ('2', 'science'), ('3', 'family')], max_length=20)),
            ],
        ),
    ]
