# Generated by Django 4.2.5 on 2023-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='category',
            field=models.CharField(choices=[('classic', '1'), ('science', '2'), ('family', '3')], max_length=20),
        ),
    ]
