# Generated by Django 4.2.5 on 2023-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_joke_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='content',
            field=models.CharField(max_length=150),
        ),
    ]
